import type { HealingNotification, SelfHealingConfig, HealingStatus, Severity } from "../types.js";

export async function sendSlackNotification(
  notification: HealingNotification,
  config: SelfHealingConfig,
): Promise<void> {
  const slackConfig = config.notifications?.slack;
  if (!slackConfig) return;

  const message = buildSlackMessage(notification, slackConfig.channel);

  if (slackConfig.webhookUrl) {
    const response = await fetch(slackConfig.webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(message),
    });
    if (!response.ok) {
      throw new Error(`Slack webhook failed: ${response.status} ${response.statusText}`);
    }
  } else if (slackConfig.token) {
    const response = await fetch("https://slack.com/api/chat.postMessage", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${slackConfig.token}`,
      },
      body: JSON.stringify(message),
    });
    if (!response.ok) {
      throw new Error(`Slack API failed: ${response.status} ${response.statusText}`);
    }
  }
}

/** @internal Exported for testing */
export function buildSlackMessage(
  notification: HealingNotification,
  channel: string,
): Record<string, unknown> {
  const { issue, analysis, testResult, pr, status, summary } = notification;
  const statusEmoji = getStatusEmoji(status);
  const severityColor = getSeverityColor(issue.severity);

  const blocks: unknown[] = [
    { type: "header", text: { type: "plain_text", text: `${statusEmoji} Self-Healing Alert` } },
    { type: "divider" },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: [
          `*${issue.title}*`,
          `*Source:* ${issue.source} | *Severity:* ${severityColor} ${issue.severity}`,
          `*Occurrences:* ${issue.occurrenceCount}${issue.affectedUsers ? ` | *Users Affected:* ${issue.affectedUsers}` : ""}`,
        ].join("\n"),
      },
    },
  ];

  if (issue.filePath) {
    blocks.push({
      type: "section",
      text: { type: "mrkdwn", text: `*File:* \`${issue.filePath}${issue.lineNumber ? `:${issue.lineNumber}` : ""}\`` },
    });
  }

  if (analysis) {
    blocks.push({ type: "divider" });
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: [
          "*Root Cause*",
          analysis.rootCause,
          "",
          "*Fix*",
          analysis.fixExplanation.substring(0, 500),
          "",
          `*Confidence:* ${Math.round(analysis.confidence * 100)}%`,
        ].join("\n"),
      },
    });
  }

  if (testResult) {
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: testResult.passed
          ? `*Tests:* :white_check_mark: All tests passed (${(testResult.durationMs / 1000).toFixed(1)}s)`
          : `*Tests:* :x: Tests failed (exit code ${testResult.exitCode})`,
      },
    });
  }

  if (pr?.url) {
    const actions: unknown[] = [
      { type: "button", text: { type: "plain_text", text: "View PR" }, url: pr.url, action_id: "view_pr" },
    ];
    if (notification.status === "pr-created") {
      actions.unshift(
        {
          type: "button",
          text: { type: "plain_text", text: "Approve & Merge" },
          style: "primary",
          action_id: `approve_${pr.number}`,
          value: String(pr.number),
        },
        {
          type: "button",
          text: { type: "plain_text", text: "Reject" },
          style: "danger",
          action_id: `reject_${pr.number}`,
          value: String(pr.number),
        },
      );
    }
    blocks.push({ type: "actions", elements: actions });
  }

  if (notification.costEstimate) {
    blocks.push({
      type: "context",
      elements: [{ type: "mrkdwn", text: `Cost: $${notification.costEstimate.totalCost.toFixed(4)} | Generated by @emisso/self-healing` }],
    });
  }

  return { channel, text: summary, blocks };
}

/** @internal Exported for testing */
export function getStatusEmoji(status: HealingStatus): string {
  switch (status) {
    case "pr-created": return "\u{1F527}";
    case "test-passed": return "\u2705";
    case "test-failed": return "\u274C";
    case "detected": return "\u{1F50D}";
    case "analyzing": return "\u{1F9E0}";
    case "merged": return "\u{1F389}";
    case "rejected": return "\u{1F6AB}";
    case "skipped": return "\u23ED\uFE0F";
    case "failed": return "\u{1F4A5}";
    default: return "\u{1F4CB}";
  }
}

/** @internal Exported for testing */
export function getSeverityColor(severity: Severity): string {
  switch (severity) {
    case "critical": return "\u{1F534}";
    case "error": return "\u{1F7E0}";
    case "warning": return "\u{1F7E1}";
    default: return "\u{1F535}";
  }
}
